name: Run Playwright Test on Chrome

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'  # Runs daily at 10 AM IST

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci  # Better than 'npm install' for CI/CD

      - name: Install only Chrome for Playwright
        run: npx playwright install chromium

      - name: Run Playwright tests
        run: npx playwright test --project=chromium
